### ISSUE TITLE
Suggestion for auto ban detection of bots

### ISSUE THREAD

**Issue by JONTTM** [leighmacdonald/gbans#110]
Quote from Kaiga:
> A plugin that bans multiple users connecting from the same IP, and also autobans anyone who uses newline characters in the chat seems like a bit of a no-brainer.

**Comment by JONTTM** [comment]
At least 4-5 bot raids in the past 48 hours on Uncletopia

**Comment by leighmacdonald** [comment]
Duplicate of #140
