### ISSUE TITLE
[Suggestion] User friendly ban command

### ISSUE THREAD

**Issue by JONTTM** [leighmacdonald/gbans#4]
!ban - When a user doesn't specify a duration, automatically make the duration permanent. 
`!ban Player1 too cool for the game` > auto assumes duration 0 and completes successfully.

!banip - When a user doesn't specify CIDR for an IP address, automatically make the CIDR /32.
`!banip 192.168.23.19 the coffee is too hot` > auto assumes 192.168.23.19/32.

**Comment by leighmacdonald** [comment]
I think the slash commands largely makes this not matter as much anymore. ReOpen if you disagree

**Comment by JONTTM** [comment]
Makes sense to me 👍
