### ISSUE TITLE
ASN blocks/bans

### ISSUE THREAD

**Issue by iBoonie** [leighmacdonald/gbans#41]
Having bans based on ASN could be useful. It would make blocking specific ISP's/Organizations a lot easier than using CIDR (some organizations can have hundreds of ipblocks and is a pain to keep updated). One can get a DB of ASN's from https://maxmind.com (account required), or https://db-ip.com/db/download/ip-to-asn-lite.

**Comment by leighmacdonald** [comment]
This is already partially supported actually, i just need to automate the loading of the datasets and decide if i want to load them into the database at all or just keep them in memory. 

Ill see if i can finish this soon, I already do this in another project so should be pretty trivial.
