### ISSUE TITLE
Check player names on connect against filtered words

### ISSUE THREAD

**Issue by leighmacdonald** [leighmacdonald/gbans#435]
Add kick/ban options for players with bad names.

**Comment by Gcommer** [comment]
I'd be down to contribute this if it's not already being worked on. Seems like I'd consume logparse.Connected in chat_repository and need to wire those warnings into the table on /admin/filters or maybe elsewhere?

Also it seems that table is just held in memory? Should that be DB backed?

**Comment by leighmacdonald** [comment]
Doing that in the chat repository is probably reasonable as the filters already exist there. https://github.com/leighmacdonald/gbans/blob/6c482391e784ae225be94e51ff7988e6c9875b16/internal/network/network_usecase.go#L81-L92 Is a option too, but i think you are probably correct to go the chat repo route.

As far as being db backed, its a nice to have. Its more important that they get kicked upon joining with an appropriate message. But i suppose something similar to the `person_messages.match_id` column could work well.
