### ISSUE TITLE
Make features optional

### ISSUE THREAD

**Issue by rjdXpxigYxNT** [leighmacdonald/gbans#479]
I just need a modern version of sourcebans' server, admin, bans, comms management panel. I would like to be able to disable the features of each individual button (such as wiki, events, contests, chatlogs, sourcetv, stats, discord, s3).

**Comment by leighmacdonald** [comment]
Yup this is a long term goal as well. Its one of the more commonly asked for feature. I don't think there was a issue created for it so i will use this one as a starting point. :+1:

**Comment by leighmacdonald** [comment]
#550 implements the baseline support for this.
