### ISSUE TITLE
ESLint 9

### ISSUE THREAD

**Issue by leighmacdonald** [leighmacdonald/gbans#481]
Migrate from ESLint 8->9. Unfortunately this uses a whole new config format because javascript libs do be like that.

This will include fixing up the included plugins as well.

**Comment by Gcommer** [comment]
Heyo, random driveby: I took a quick look at this, seems this is currently blocked on https://github.com/jsx-eslint/eslint-plugin-react/issues/3699

Also typescript-eslint has v9 support, but only on alpha releases, which you may not be comfortable with: https://github.com/typescript-eslint/typescript-eslint/issues/8211

**Comment by leighmacdonald** [comment]
Hey, Yeah i've had some reasonable success with the alpha version in a smaller, very simple, project with a similar stack i work on. Its, however, probably worth waiting another month or so at least before tackling this on here. The amount of plugins that fully supported 9 was still a bit hit or miss, and i am using a few more here, though i did get to a pretty reasonable place after a bit of struggle, so its pretty close for sure.
