### ISSUE TITLE
Support local file serving

### ISSUE THREAD

**Issue by leighmacdonald** [leighmacdonald/gbans#485]
Most people will likely not want to serve from s3 buckets. This would enable a option to choose between traditional file serving and s3.

**Comment by rjdXpxigYxNT** [comment]
would this do fastdl as well?

**Comment by leighmacdonald** [comment]
This is not going to be well suited for that use case since urls paths use a UUID and not a file name (helps to prevent some enumeration attacks among other things), so the game server would need to somehow map that. In generally fastdl should be handled by the web server sitting in front of the app either proxying a sub path or on another subdomain.
