### ISSUE TITLE
First time setup

### ISSUE THREAD

**Issue by rjdXpxigYxNT** [leighmacdonald/gbans#493]
Nowhere mentions requiring to run `./gbans setup` after `./gbans serve` to set up things such as owner permissions. Should it be moved to `serve` with a first time check?

**Comment by leighmacdonald** [comment]
Moving stuff into the serve command is probably reasonable, but i have not really thought about it much yet. 

However, longer term i think that it will be more automated as i eventually want to move most of the static config file directly into the database anyways.
