### ISSUE TITLE
[Suggestion] Allow banning of multiple accounts in one command

### ISSUE THREAD

**Issue by JONTTM** [leighmacdonald/gbans#5]

**Comment by leighmacdonald** [comment]
I'm not sure i see a reason for this.  If you are trying to kick many, its almost certainly a bot which should be banip'd instead.

**Comment by JONTTM** [comment]
If the bots are now kicked by IP ban then this is not necessary. Previously, the bots were not getting kicked so we banned all the Steam IDs individually to kick them one-by-one.
