### ISSUE TITLE
Random kicks on seemingly innocent messages

### ISSUE THREAD

**Issue by crescentrose** [leighmacdonald/gbans#71]
(I mostly copy-pasted this from a message I sent to Jon, sorry for poor formatting).

I found an issue with gbans that might lead to people being randomly kicked from the server, as described in this [Uncle Dane Discord chat](https://discord.com/channels/132353223125106688/722832493648150558/843506029429653536).

Basically [here you use a regex match](https://github.com/leighmacdonald/gbans/blob/70117d0405e35c877400b6b0cbd4ef3f2d40c05d/internal/service/filters.go#L59), and the file that [you're importing](https://github.com/leighmacdonald/uncletopia/blob/master/roles/system/templates/gbans.yml.j2#L39) is full of what one might consider a "shitty regex" (e.g. `s.o.b.` will match words that you might not want matched), as well as things that people might not even consider as swear words (e.g. `damn`, `lmfao`). Another issue is that they aren't anchored so you run into the classic Scunthorpe problem.

The players aren't warned of anything in chat, so i can't test if my theory is true or not but if it is there should be a bunch of warnings in your discord channel.

You can check out the regexes that [this plugin uses](https://github.com/JoinedSenses/SM-Regex-Trigger/blob/f5607ac94d11bef93380b3566ac0dbed9092ed41/configs/regextriggers/regextriggers.cfg#L614), they make much more sense than just importing the "bad words" list.

**Comment by leighmacdonald** [comment]
Thanks, though the issue is not exactly as you describe. The list that you are linking to, im not actually using. It was just a remnant of a older test of word lists. As yes, that list is pretty bad as-is.

I am aware of the issue you are describing though and am looking into it, thanks.
