### ISSUE TITLE
Add option for auto banning certain types of events

### ISSUE THREAD

**Issue by JONTTM** [leighmacdonald/gbans#8]
This is more specific to Uncletopia, but the bots always join with the same IP, so we could detect if several users join quickly on the same IP and automatically ban them.

**Comment by leighmacdonald** [comment]
This is likely not something we want to do since real players can come across this. "Lets have a lan party" "Lets all join uncletopia" "wtf!!!"

**Comment by JONTTM** [comment]
I meant within a very short span of time (less than a second). If 10 accounts join from the same IP in less than a second it's 99.99% bot accounts.
