### ISSUE TITLE
Investigate resource usage by gbans with new stat tracking abilities 

### ISSUE THREAD

**Issue by JONTTM** [leighmacdonald/gbans#96]
We should add some sort of tracking to Grafana that specifically tracks gbans resource usage on the server with all the new stat tracking. Maybe some logging for what gbans is doing at the time so it's easier to debug and optimize in the future.

**Comment by leighmacdonald** [comment]
Well the relay itself does very little cpu wise. But either way, this is probably out of scope for gbans. The grafana node_exporter metrics we already have should be enough. You can add more alters for stuff like CPU usage.

**Comment by JONTTM** [comment]
Is there anyway we could add process tracking to Grafana then? Something that would track specific processes that use too much CPU or network

**Comment by leighmacdonald** [comment]
node_exporter does not do that no. You can run https://github.com/ncabatoff/process-exporter if you want to export those stats
